### ISSUE TITLE
-PオプションはGNUのgrepでのみ動作

### ISSUE THREAD

**Issue by arks22** [b4b4r07/zsh-gomi#3]
日本語で失礼します。
https://github.com/b4b4r07/zsh-gomi/blob/master/bin/gomi#L176
ですが、
grep -PはGNU版のgrepでしか動作せず、BSDの場合動かないので、README等にその旨をお書きになってはいかかでしょうか。

**Comment by babarot** [comment]
ありがとうございます。
恐らくタブ文字 `\t` をタブとして使用したいがために `-P` を指定しているはずなので、POSIX に沿った指定方法に変えました。

GNU grep を必要としなくなったため、README 等への記載はありません。
報告ありがとうございました。

**Comment by arks22** [comment]
こちらの環境だと修正箇所が原因で新たな不具合を起こしています。
`mv: rename  to : No such file or directory`
とエラーが出るので、やはり修正箇所あたりが原因だと思われます。
タブ文字を使用するのに`$'\t`を使わずに直接タブ文字を入力してみてはいかがでしょうか。
http://d.hatena.ne.jp/bettamodoki/20120220/1329732301

**Comment by babarot** [comment]
@arks22 ご指摘にある通り修正いたしました。あまりエレガントな解決方法でもないので、近いうち根本的に見直すかもしれません。
